; -------------------------------------------------------------------------
; PLATFORMIO CONFIGURATION FILE
; PDR Project- No GNSS Localisation
; -------------------------------------------------------------------------

[platformio]
src_dir = src

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; first environment for "Anchor" ESP type 
[env:ancre]
; only compile src/ancre
build_src_filter = +<ancre/> -<robot/>
build_flags = 
    -D ROLE_ANCRE
    
; Second environment for "Robot" ESP type 
[env:robot]
; only compile src/robot/
build_src_filter = +<robot/> -<ancre/>

build_flags = 
    -D ROLE_ROBOT

; libs for Robot
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^6.21.3

board_build.partitions = huge_app.csv ; program was too big for the memory, had to expand main partition and remove update partitions